# hello-world-objs := hello-world-kernel.o
# obj-m := hello-world.o
#control-GPIO-module-objs := control-GPIO.o
#obj-m := control-GPIO-module.o
deviceFile-objs := deviceFileTest.o
obj-m := deviceFile.o
